name: Prettier Check

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check . --arrow-parens=always --bracket-spacing --end-of-line=lf --html-whitespace-sensitivity=css --insert-pragma=false --single-attribute-per-line=false --bracket-same-line=false --jsx-bracket-same-line=false --jsx-single-quote=false --print-width=80 --prose-wrap=preserve --quote-props=as-needed --require-pragma=false --semi=true --single-quote=false --tab-width=2 --trailing-comma=es5 --use-tabs=false --embedded-language-formatting=auto --vue-indent-script-and-style=false --parser=babel
